import { create } from 'zustand';
import { api } from '../api';
import type { 
  LearningComponent, 
  LearningPath, 
  CanvasNode, 
  CanvasEdge, 
  NodePosition 
} from '../types';

interface SimulationState {
  currentNodeId: string | null;
  metrics: Record<string, any>;
  visitedNodeIds: string[];
  evaluationError: string | null;
}

interface StoreState {
  components: LearningComponent[];
  learningPaths: LearningPath[];
  activePath: LearningPath | null;
  selectedNodeId: string | null;
  selectedEdgeId: string | null;
  isDirty: boolean;
  isLoading: boolean;
  error: string | null;
  
  // Simulation
  isSimulating: boolean;
  simulationState: SimulationState;

  // Actions
  loadComponents: () => Promise<void>;
  loadLearningPaths: () => Promise<void>;
  loadPath: (id: string) => Promise<void>;
  createNewPath: () => void;
  deletePath: (id: string) => Promise<void>;
  saveActivePath: () => Promise<void>;
  setActivePathField: (field: 'name' | 'description' | 'status', value: string) => void;
  
  // Canvas Actions
  addNode: (node: Omit<CanvasNode, 'id'>) => void;
  updateNodePosition: (id: string, position: NodePosition) => void;
  updateNodeLabel: (id: string, label: string) => void;
  updateNodeComponent: (id: string, componentId: string | null) => void;
  deleteNode: (id: string) => void;
  
  addEdge: (edge: Omit<CanvasEdge, 'id'>) => boolean;
  updateEdge: (id: string, fields: Partial<CanvasEdge>) => void;
  deleteEdge: (id: string) => void;
  
  selectNode: (id: string | null) => void;
  selectEdge: (id: string | null) => void;
  clearSelection: () => void;
  
  // Simulation Actions
  startSimulation: () => void;
  stopSimulation: () => void;
  setSimulationMetric: (key: string, value: any) => void;
  stepSimulation: () => Promise<void>;
}

const initialSimulationState = (): SimulationState => ({
  currentNodeId: null,
  metrics: {
    score: 50,
    score_range: 50,
    passed: true,
    completion: true
  },
  visitedNodeIds: [],
  evaluationError: null
});

export const useStore = create<StoreState>((set, get) => ({
  components: [],
  learningPaths: [],
  activePath: null,
  selectedNodeId: null,
  selectedEdgeId: null,
  isDirty: false,
  isLoading: false,
  error: null,
  
  isSimulating: false,
  simulationState: initialSimulationState(),

  loadComponents: async () => {
    set({ isLoading: true, error: null });
    try {
      const data = await api.getComponents();
      set({ components: data.items, isLoading: false });
    } catch (err: any) {
      set({ error: err.message || 'Failed to load components', isLoading: false });
    }
  },

  loadLearningPaths: async () => {
    set({ isLoading: true, error: null });
    try {
      const data = await api.getAllLearningPaths();
      set({ learningPaths: data, isLoading: false });
    } catch (err: any) {
      set({ error: err.message || 'Failed to load learning paths', isLoading: false });
    }
  },

  loadPath: async (id: string) => {
    set({ isLoading: true, error: null, selectedNodeId: null, selectedEdgeId: null, isSimulating: false });
    try {
      const path = await api.getLearningPath(id);
      // Ensure nodes and edges are initialized as lists
      if (!path.nodes) path.nodes = [];
      if (!path.edges) path.edges = [];
      if (!path.canvas) path.canvas = { zoom: 1, offsetX: 0, offsetY: 0 };
      set({ activePath: path, isDirty: false, isLoading: false });
    } catch (err: any) {
      set({ error: err.message || 'Failed to load path', isLoading: false });
    }
  },

  createNewPath: () => {
    const newPath: LearningPath = {
      id: '', // Will be generated by backend or on save
      name: 'Untitled Learning Path',
      description: '',
      status: 'draft',
      canvas: { zoom: 1.0, offsetX: 0, offsetY: 0 },
      nodes: [
        {
          id: 'node-start',
          type: 'start',
          label: 'Start',
          position: { x: 300, y: 80 },
          componentId: null
        },
        {
          id: 'node-end',
          type: 'end',
          label: 'End',
          position: { x: 310, y: 350 },
          componentId: null
        }
      ],
      edges: []
    };
    set({
      activePath: newPath,
      selectedNodeId: null,
      selectedEdgeId: null,
      isDirty: true,
      isSimulating: false,
      simulationState: initialSimulationState()
    });
  },

  deletePath: async (id: string) => {
    set({ isLoading: true, error: null });
    try {
      await api.deleteLearningPath(id);
      const active = get().activePath;
      set((state) => ({
        learningPaths: state.learningPaths.filter((p) => p.id !== id),
        activePath: active && active.id === id ? null : active,
        selectedNodeId: active && active.id === id ? null : state.selectedNodeId,
        selectedEdgeId: active && active.id === id ? null : state.selectedEdgeId,
        isLoading: false
      }));
    } catch (err: any) {
      set({ error: err.message || 'Failed to delete path', isLoading: false });
    }
  },

  saveActivePath: async () => {
    const { activePath } = get();
    if (!activePath) return;
    set({ isLoading: true, error: null });
    try {
      const saved = await api.saveLearningPath(activePath);
      set((state) => {
        const index = state.learningPaths.findIndex((p) => p.id === saved.id);
        const updatedPaths = [...state.learningPaths];
        if (index > -1) {
          updatedPaths[index] = saved;
        } else {
          updatedPaths.push(saved);
        }
        return {
          activePath: saved,
          learningPaths: updatedPaths,
          isDirty: false,
          isLoading: false
        };
      });
    } catch (err: any) {
      set({ error: err.message || 'Failed to save path', isLoading: false });
    }
  },

  setActivePathField: (field, value) => {
    set((state) => {
      if (!state.activePath) return {};
      return {
        activePath: {
          ...state.activePath,
          [field]: value
        },
        isDirty: true
      };
    });
  },

  addNode: (node) => {
    set((state) => {
      if (!state.activePath) return {};
      const newId = `node-${Date.now().toString().substring(8)}`;
      const newNode: CanvasNode = {
        ...node,
        id: newId
      };
      return {
        activePath: {
          ...state.activePath,
          nodes: [...state.activePath.nodes, newNode]
        },
        selectedNodeId: newId,
        selectedEdgeId: null,
        isDirty: true
      };
    });
  },

  updateNodePosition: (id, position) => {
    set((state) => {
      if (!state.activePath) return {};
      return {
        activePath: {
          ...state.activePath,
          nodes: state.activePath.nodes.map((node) => 
            node.id === id ? { ...node, position } : node
          )
        },
        isDirty: true
      };
    });
  },

  updateNodeLabel: (id, label) => {
    set((state) => {
      if (!state.activePath) return {};
      return {
        activePath: {
          ...state.activePath,
          nodes: state.activePath.nodes.map((node) => 
            node.id === id ? { ...node, label } : node
          )
        },
        isDirty: true
      };
    });
  },

  updateNodeComponent: (id, componentId) => {
    set((state) => {
      if (!state.activePath) return {};
      
      // Look up component details to sync node label if name is generic
      const comp = state.components.find((c) => c.id === componentId);
      const nodeToUpdate = state.activePath.nodes.find((n) => n.id === id);
      let updatedLabel = nodeToUpdate?.label || '';
      
      if (comp && (!nodeToUpdate?.label || nodeToUpdate.label.startsWith('Node') || nodeToUpdate.label === 'Unit' || nodeToUpdate.label === 'Assessment')) {
        updatedLabel = comp.title;
      }

      return {
        activePath: {
          ...state.activePath,
          nodes: state.activePath.nodes.map((node) => 
            node.id === id ? { ...node, componentId, label: updatedLabel } : node
          )
        },
        isDirty: true
      };
    });
  },

  deleteNode: (id) => {
    if (id === 'node-start' || id === 'node-end') return; // Cannot delete start/end
    set((state) => {
      if (!state.activePath) return {};
      return {
        activePath: {
          ...state.activePath,
          nodes: state.activePath.nodes.filter((node) => node.id !== id),
          edges: state.activePath.edges.filter(
            (edge) => edge.sourceNodeId !== id && edge.targetNodeId !== id
          )
        },
        selectedNodeId: state.selectedNodeId === id ? null : state.selectedNodeId,
        isDirty: true
      };
    });
  },

  addEdge: (edge) => {
    // Avoid self connections
    if (edge.sourceNodeId === edge.targetNodeId) return false;
    
    const active = get().activePath;
    if (!active) return false;
    
    // Check if edge already exists
    const duplicate = active.edges.find(
      (e) => e.sourceNodeId === edge.sourceNodeId && e.targetNodeId === edge.targetNodeId
    );
    if (duplicate) return false;

    const newId = `edge-${Date.now().toString().substring(8)}`;
    const newEdge: CanvasEdge = {
      ...edge,
      id: newId,
      isDefault: edge.isDefault ?? false,
      priority: edge.priority ?? 1,
      conditions: edge.conditions ?? { operator: 'AND', rules: [] }
    };

    set((state) => {
      if (!state.activePath) return {};
      return {
        activePath: {
          ...state.activePath,
          edges: [...state.activePath.edges, newEdge]
        },
        isDirty: true
      };
    });
    return true;
  },

  updateEdge: (id, fields) => {
    set((state) => {
      if (!state.activePath) return {};
      return {
        activePath: {
          ...state.activePath,
          edges: state.activePath.edges.map((edge) => 
            edge.id === id ? { ...edge, ...fields } : edge
          )
        },
        isDirty: true
      };
    });
  },

  deleteEdge: (id) => {
    set((state) => {
      if (!state.activePath) return {};
      return {
        activePath: {
          ...state.activePath,
          edges: state.activePath.edges.filter((edge) => edge.id !== id)
        },
        selectedEdgeId: state.selectedEdgeId === id ? null : state.selectedEdgeId,
        isDirty: true
      };
    });
  },

  selectNode: (id) => {
    set({ selectedNodeId: id, selectedEdgeId: null });
  },

  selectEdge: (id) => {
    set({ selectedEdgeId: id, selectedNodeId: null });
  },

  clearSelection: () => {
    set({ selectedNodeId: null, selectedEdgeId: null });
  },

  startSimulation: () => {
    const { activePath } = get();
    if (!activePath) return;
    
    // Find start node
    const startNode = activePath.nodes.find((n) => n.type === 'start');
    if (!startNode) {
      set({ error: 'Cannot simulate: Path has no start node' });
      return;
    }

    set({
      isSimulating: true,
      selectedNodeId: startNode.id,
      selectedEdgeId: null,
      simulationState: {
        currentNodeId: startNode.id,
        metrics: {
          score: 75,
          score_range: 75,
          passed: true,
          completion: true
        },
        visitedNodeIds: [startNode.id],
        evaluationError: null
      }
    });
  },

  stopSimulation: () => {
    set({
      isSimulating: false,
      simulationState: initialSimulationState()
    });
  },

  setSimulationMetric: (key, value) => {
    set((state) => ({
      simulationState: {
        ...state.simulationState,
        metrics: {
          ...state.simulationState.metrics,
          [key]: value
        }
      }
    }));
  },

  stepSimulation: async () => {
    const { activePath, simulationState } = get();
    if (!activePath || !simulationState.currentNodeId) return;
    
    // If we've reached an end node, there is nowhere to step
    const currNode = activePath.nodes.find((n) => n.id === simulationState.currentNodeId);
    if (currNode && currNode.type === 'end') {
      set((state) => ({
        simulationState: {
          ...state.simulationState,
          evaluationError: 'Already reached the End node!'
        }
      }));
      return;
    }

    set({ isLoading: true });
    
    try {
      const result = await api.evaluateNextNode(activePath.id, {
        currentNodeId: simulationState.currentNodeId,
        metrics: simulationState.metrics
      });

      set((state) => {
        const nextNodeId = result.nextNodeId;
        if (!nextNodeId) {
          return {
            isLoading: false,
            simulationState: {
              ...state.simulationState,
              evaluationError: 'No matching path transition found. Evaluation returned null.'
            }
          };
        }
        
        return {
          isLoading: false,
          selectedNodeId: nextNodeId,
          simulationState: {
            ...state.simulationState,
            currentNodeId: nextNodeId,
            visitedNodeIds: [...state.simulationState.visitedNodeIds, nextNodeId],
            evaluationError: null
          }
        };
      });
    } catch (err: any) {
      set((state) => ({
        isLoading: false,
        simulationState: {
          ...state.simulationState,
          evaluationError: err.response?.data?.message || 'Error occurred during evaluation.'
        }
      }));
    }
  }
}));
