spring.application.name=Adaptive-Learning-Path-Builder

# SQLite Database
spring.datasource.url=jdbc:sqlite:learning-builder.db
spring.datasource.driver-class-name=org.sqlite.JDBC

# Hibernate
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

# SQL Logging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Disable Open Session in View
spring.jpa.open-in-view=false

# CORS Allowed Origins
app.cors.allowed-origins=${APP_CORS_ALLOWED_ORIGINS:http://localhost:5173}